#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative 'file_list_getter'
require_relative 'file_formatter'


opt = OptionParser.new
options = {}
opt.on('-a', '--all', 'Show all files including hidden files') { options[:show_all] = true }
opt.on('-r', '--reverse', 'Sort files in reverse order') { options[:reverse] = true }
opt.on('-l', '--long', 'Display files in long format') { options[:long_format] = true }
opt.parse!(ARGV)

file_list_getter = FileListGetter.new(show_all: options[:show_all], reverse: options[:reverse])
files = file_list_getter.list_files
file_formatter = FileFormatter.new(files, long_format: options[:long_format])
file_formatter.output
