#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative 'file_list_getter'
require_relative 'file_formatter'

opt = OptionParser.new
options = {}
opt.on('-a', '--all', 'Show all files including hidden files') { options[:show_all] = true }
opt.on('-r', '--reverse', 'Sort files in reverse order') { options[:reverse] = true }
opt.on('-l', '--long', 'Display files in long format') { options[:long_format] = true }
opt.parse!(ARGV)

file_list_getter = FileListGetter.new(show_all: options[:show_all], reverse: options[:reverse])
files = file_list_getter.list_files

file_formatter = FileFormatter.new(files, long_format: options[:long_format])

if options[:long_format]
  puts "合計 #{file_formatter.format[:total_blocks]}"
  file_formatter.format[:lines].each do |line|
    puts line
  end
else
  matrix_file_names = file_formatter.format[:matrix_file_names]
  col_max_lengths = file_formatter.format[:col_max_lengths]
  matrix_file_names.each do |row|
    row.each_with_index do |file, col|
      print file.to_s.ljust(col_max_lengths[col] + 2)
    end
    puts
  end
end
